#服务名称
spring:
  application:
    name: hengboy-spring-cloud-eureka

#服务端口
server:
  port: 8958

#euraka的配置
eureka:
  client:
    # 是否从其他的服务中心同步服务列表
    fetch-registry: false
    # 是否把自己作为服务注册到其他服务注册中心
    register-with-eureka: false
service-url:
  defaultZone: http://localhost:${server.port}/eureka