eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8958/eureka/  #服务注册地址
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/gitee_zym/springcloud_config_server.git #配置git仓库地址
          search-paths: /gitee_zym/springcloud_config_server.git #配置仓库路径
          username: gitee_zym #访问git仓库的用户名，公开仓库可不填
          password: gitee123. #访问git仓库的用户密码，公开仓库可不填
      label: master #配置仓库的分支
server:
  port: 8888