eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8958/eureka/  #服务注册地址
server:
  port: 8769  #微服务的端口
spring:
  application:
    name: service-zuul
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
zuul:
  routes:
    api-a:
      path: /api-a/**
      service-id: service-ribbon
    api-b:
      path: /api-b/**
      service-id: service-fein
  host:
    connect-timeout-millis: 5000
    socket-timeout-millis: 5000