eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8958/eureka/  #服务注册地址
server:
  port: 8765  #微服务的端口
spring:
  application:
    name: service-fein
feign:
  hystrix:
    enabled: false #断路器开关